# Rustfmt configuration aligned with .editorconfig
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
wrap_comments = true
match_block_trailing_comma = true
trailing_semicolon = true
trailing_comma = "Vertical"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = "Auto"
binop_separator = "Front"
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
fn_single_line = false
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
license_template_path = ""
format_generated_files = false
