version: "3"
services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld

  # Outerbase Studio - A lightweight database GUI for viewing and managing libSQL
  # Access at http://localhost:3000
  # To connect to libSQL, use:
  #   - Connection Type: LibSQL/Turso
  #   - URL: http://libsql:8080
  outerbase-studio:
    build:
      context: https://github.com/outerbase/studio.git#develop
    ports:
      - "3000:3000"
    depends_on:
      - libsql
