query GetExpenses($first: Int!, $offset: Int!) {
    expenses(first: $first, offset: $offset) {
        id
        title
        amount
        expenseDate
        categoryId
        costCenterId
        description
        createdAt
        updatedAt
        category {
            id
            name
        }
        costCenter {
            id
            name
            code
        }
    }
    totalExpenses
}

query GetPurchaseCategoriesForExpenses {
    allPurchaseCategories {
        id
        name
    }
}

query GetCostCentersForExpenses {
    allCostCenters {
        id
        name
        code
        state
    }
}

query GetExpensesByCategory($categoryId: DbUuid!, $first: Int!, $offset: Int!) {
    expensesByCategory(categoryId: $categoryId, first: $first, offset: $offset) {
        id
        title
        amount
        expenseDate
        categoryId
        costCenterId
        description
        createdAt
        updatedAt
        category {
            id
            name
        }
        costCenter {
            id
            name
            code
        }
    }
}

mutation CreateExpense($input: ExpenseNewInput!) {
    createExpense(expense: $input) {
        id
        title
        amount
        expenseDate
        categoryId
        costCenterId
        description
        createdAt
        updatedAt
        category {
            id
            name
        }
        costCenter {
            id
            name
            code
        }
    }
}

mutation UpdateExpense($input: ExpenseUpdateInput!) {
    updateExpense(expense: $input) {
        id
        title
        amount
        expenseDate
        categoryId
        costCenterId
        description
        createdAt
        updatedAt
        category {
            id
            name
        }
        costCenter {
            id
            name
            code
        }
    }
}

mutation DeleteExpense($id: DbUuid!) {
    deleteExpense(id: $id)
}
